/**
 * /api/clients — Vercel serverless function. Admin-only.
 *
 * The saved-clients address book behind /send's client picker. Same
 * "one small JSON blob is the database" pattern as the delivery manifests:
 * the whole list lives at clients/index.json in Vercel Blob, and avatars
 * live under clients/avatars/<id>.* (uploaded browser-side through
 * api/deliver-upload-token.js, which allows that prefix for exactly this).
 *
 *   GET                                  -> { ok, clients: [...] }
 *   POST { action:'save', id?, name, avatarUrl? }  -> upsert, returns the client
 *   POST { action:'delete', id }         -> removes it + its avatar blobs
 *
 * One admin, low write volume — a read-modify-write on one blob is fine here
 * the same way it is for manifests. Each client: { id, name, avatarUrl,
 * createdAt, updatedAt }.
 */
import { list, del } from '@vercel/blob';
import { requireAdmin } from './_lib/adminAuth.mjs';
import { readClientsIndex, writeClientsIndex } from './_lib/clientsIndex.mjs';

const MAX_CLIENTS = 500;
// Client ids: generated by randomId() below, or supplied by /send (it makes
// one up-front so the avatar can upload before the save call — one write to
// the index per save instead of two racing ones).
const ID_RE = /^[a-z0-9]{6,32}$/;

/* Index read/write lives in _lib/clientsIndex.mjs — versioned files, never
   an in-place overwrite. See that file for the DuVine story. */

/* Same rule as deliver-create's cleanThumbUrl: this URL goes straight into an
   <img src> on pages we serve (/send and the client-facing /receive), so only
   our own Blob store is ever accepted. Fails closed to "no avatar". */
function cleanAvatarUrl(v) {
  if (typeof v !== 'string' || v.length > 500) return null;
  try {
    const u = new URL(v);
    if (u.protocol !== 'https:') return null;
    if (!/(^|\.)blob\.vercel-storage\.com$/.test(u.hostname)) return null;
    return u.href;
  } catch (e) {
    return null;
  }
}

function randomId() {
  const alphabet = 'abcdefghjkmnpqrstuvwxyz23456789';
  const bytes = crypto.getRandomValues(new Uint8Array(10));
  return Array.from(bytes, (b) => alphabet[b % alphabet.length]).join('');
}

export default async function handler(req, res) {
  if (requireAdmin(req, res)) return;

  if (req.method === 'GET') {
    try {
      const clients = await readClientsIndex();
      clients.sort((a, b) => String(a.name).localeCompare(String(b.name), undefined, { sensitivity: 'base' }));
      return res.status(200).json({ ok: true, clients });
    } catch (err) {
      console.error('Client list failed', err);
      return res.status(502).json({ error: 'Could not load clients.' });
    }
  }

  if (req.method !== 'POST') {
    res.setHeader('Allow', 'GET, POST');
    return res.status(405).json({ error: 'Method not allowed' });
  }

  let data = req.body;
  if (typeof data === 'string') {
    try { data = JSON.parse(data); } catch (e) { data = null; }
  }
  if (!data || typeof data !== 'object') {
    return res.status(400).json({ error: 'Bad request' });
  }

  try {
    if (data.action === 'save') {
      const name = String(data.name || '').trim().slice(0, 200);
      if (!name) return res.status(400).json({ error: 'A client needs a name.' });
      const avatarUrl = cleanAvatarUrl(data.avatarUrl);
      // /send generates the id up-front so the avatar can upload BEFORE this
      // call — the whole save is then ONE index write, not two racing ones.
      const givenId = ID_RE.test(String(data.id || '')) ? String(data.id) : null;
      const clients = await readClientsIndex();
      const now = new Date().toISOString();

      let client = givenId ? clients.find((c) => c.id === givenId) : null;
      /* Upsert by name too (case-insensitive) so typing "Duvine" twice never
         creates a second "DuVine" — the picker treats names as identity. */
      if (!client) {
        client = clients.find((c) => String(c.name).toLowerCase() === name.toLowerCase());
      }
      if (client) {
        client.name = name;
        if (avatarUrl) client.avatarUrl = avatarUrl;
        else if (data.avatarUrl === null) client.avatarUrl = null; // explicit removal
        client.updatedAt = now;
      } else {
        if (clients.length >= MAX_CLIENTS) {
          return res.status(400).json({ error: 'Client list is full.' });
        }
        client = { id: givenId || randomId(), name, avatarUrl: avatarUrl || null, createdAt: now, updatedAt: now };
        clients.push(client);
      }
      await writeClientsIndex(clients);
      return res.status(200).json({ ok: true, client });
    }

    if (data.action === 'delete') {
      const id = String(data.id || '');
      if (!id) return res.status(400).json({ error: 'Bad request' });
      const clients = await readClientsIndex();
      const next = clients.filter((c) => c.id !== id);
      if (next.length !== clients.length) await writeClientsIndex(next);
      /* Best-effort avatar cleanup — the index is already consistent, and an
         orphaned avatar blob costs kilobytes, not correctness. */
      try {
        const { blobs } = await list({ prefix: 'clients/avatars/' + id, limit: 10 });
        if (blobs.length) await del(blobs.map((b) => b.url));
      } catch (e) {
        console.warn('Avatar cleanup skipped for client ' + id, e);
      }
      return res.status(200).json({ ok: true });
    }

    return res.status(400).json({ error: 'Unknown action' });
  } catch (err) {
    console.error('Client save failed', err);
    return res.status(502).json({ error: 'Could not save. Please try again.' });
  }
}
